apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bookstore-api
  name: bookstore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookstore-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: bookstore-api
    spec:
      containers:
        - env:
            - name: API_GATEWAY_URL
              value: http://bs-gateway:8080
            - name: PORT
              value: "5000"
          image: bookstore-api
          imagePullPolicy: IfNotPresent
          name: bookstore-api
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
