apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bs-gateway
  name: bs-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bs-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: bs-gateway
    spec:
      containers:
        - env:
            - name: BS_API_URL
              value: http://bookstore-api:5000
            - name: BS_INVENTORY_URL
              value: http://bookstore-inventory:5000
            - name: PORT
              value: "8080"
          image: bs-gateway
          imagePullPolicy: IfNotPresent
          name: bs-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9876
              protocol: TCP
      restartPolicy: Always
