import Head from 'next/head'
import Image from 'next/image'
import localFont from 'next/font/local'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Bookstore CMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <main className="flex min-h-screen flex-col items-center justify-center">
          <Image
            src="/images/home-illustration.webp"
            alt="Next.js logo"
            width={380}
            height={380}
            priority
            className="mb-4 rounded-lg"
          />
          <p className="text-center mb-4">
            Hello! Ready to organize your bookstore and keep your readers happy?
            <br />
            Let’s get started
          </p>

          <Link href="/books">
            <Button>Get Started</Button>
          </Link>
        </main>
      </div>
    </>
  )
}
