apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bookstore-inventory
  name: bookstore-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookstore-inventory
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: bookstore-inventory
    spec:
      containers:
        - image: bookstore-inventory
          imagePullPolicy: IfNotPresent
          name: bookstore-inventory
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: bs-inventory-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bs-secret
                  key: POSTGRES_PASSWORD
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bookstore-inventory
  name: bookstore-inventory
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: bookstore-inventory
