apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bs-auth
  name: bs-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: bs-auth
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: bs-auth
    spec:
      containers:
        - image: bs-auth
          imagePullPolicy: IfNotPresent
          name: bs-auth
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: bs-config
            - configMapRef:
                name: bs-auth-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bs-secret
                  key: POSTGRES_PASSWORD
            - name: SUPABASE_SERVICE_ROLE
              valueFrom:
                secretKeyRef:
                  name: bs-secret
                  key: SUPABASE_SERVICE_ROLE
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: bs-secret
                  key: SUPABASE_KEY
          resources:
            requests:
              memory: "64Mi"
              cpu: "80m"
            limits:
              memory: "128Mi"
              cpu: "80m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: bs-auth
  name: bs-auth
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: bs-auth
