apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-config
data:
  POSTGRES_USER: postgres.wngxlnbywzluwfbqekua
  POSTGRES_HOST: aws-0-us-east-1.pooler.supabase.com
  POSTGRES_PORT: '5432'
  API_GATEWAY_URL: http://bs-gateway:8080
  SUPABASE_URL: https://wngxlnbywzluwfbqekua.supabase.co

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-auth-config
data:
  POSTGRES_DB: bs_auth
  PORT: '5000'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-api-config
data:
  POSTGRES_DB: bs_api
  PORT: '5000'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-inventory-config
data:
  POSTGRES_DB: bs_inventory
  PORT: '5000'

# configmap for bookstore-cms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-cms-config
data:
  API_GATEWAY_URL: http://bs-gateway:8080

# configmap for bs-order
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-order-config
data:
  POSTGRES_DB: bs_order
  PORT: '5000'