apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: bs-gateway
  name: bs-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bs-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: bs-gateway
    spec:
      containers:
        - name: bs-gateway
          image: bs-gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9876
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "80m"
            limits:
              memory: "128Mi"
              cpu: "80m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: bs-gateway
  name: bs-gateway
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9876"
      port: 9876
      targetPort: 9876
  selector:
    app: bs-gateway

# Load Balancer
---
apiVersion: v1
kind: Service
metadata:
  name: bs-gateway-lb
spec:
  type: LoadBalancer
  selector:
    app: bs-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080