apiVersion: apps/v1
kind: Deployment
metadata:
  name: bs-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bs-order
  template:
    metadata:
      labels:
        app: bs-order
    spec:
      containers:
        - name: bs-order
          image: bs-order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "80m"
            limits:
              memory: "128Mi"
              cpu: "80m"
          envFrom:
            - configMapRef:
                name: bs-config
            - configMapRef:
                name: bs-order-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bs-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: bs-order
spec:
  selector:
    app: bs-order
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  type: ClusterIP