apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-db-config
data:
  POSTGRES_USER: bsdbuser

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-db-init-config
data:
  init.sql: |
    CREATE DATABASE bs_api;
    GRANT ALL PRIVILEGES ON DATABASE bs_api TO bsdbuser;
    CREATE DATABASE bs_inventory;
    GRANT ALL PRIVILEGES ON DATABASE bs_inventory TO bsdbuser;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-api-config
data:
  POSTGRES_DB: bs_api
  POSTGRES_USER: bsdbuser
  POSTGRES_HOST: postgres-0.postgres
  POSTGRES_PORT: '5432'
  API_GATEWAY_URL: http://bs-gateway:8080
  PORT: '5000'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-inventory-config
data:
  POSTGRES_DB: bs_inventory
  POSTGRES_USER: bsdbuser
  POSTGRES_HOST: postgres-0.postgres
  POSTGRES_PORT: '5432'
  API_GATEWAY_URL: http://bs-gateway:8080
  PORT: '5000'