http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: '*'
    paths: '/api/*'
serviceEndpoints:
  bs_api_svc:
    url: ${BS_API_URL:-'http://localhost:5001'}
  bs_inventory_svc:
    url: ${BS_INVENTORY_URL:-'http://localhost:5002'}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - condition:
              name: pathMatch
              pattern: "/api/books/*"
            action:
              serviceEndpoint: bs_api_svc
          - condition:
              name: pathMatch
              pattern: "/api/inventory/*"
            action:
              serviceEndpoint: bs_inventory_svc
